---
zabbix_version: "7.0"
zabbix_repository_distribution: "{{ 'ubuntu' if ansible_distribution == 'Ubuntu' else 'debian' }}"
zabbix_repository_family: "{{ zabbix_repository_distribution ~ ('-arm64' if ansible_architecture in ['aarch64', 'arm64'] else '') }}"
zabbix_repository_package_url: "{{ 'https://repo.zabbix.com/zabbix/' ~ zabbix_version ~ '/' ~ zabbix_repository_family ~ '/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu' ~ ansible_distribution_version ~ '_all.deb' if ansible_distribution == 'Ubuntu' else 'https://repo.zabbix.com/zabbix/' ~ zabbix_version ~ '/' ~ zabbix_repository_family ~ '/pool/main/z/zabbix-release/zabbix-release_latest_' ~ zabbix_version ~ '+debian' ~ ansible_distribution_major_version ~ '_all.deb' }}"
zabbix_repository_package_path: "/tmp/zabbix-release-{{ zabbix_version }}-{{ ansible_distribution | lower }}{{ ansible_distribution_version }}.deb"
zabbix_php_version: "{{ '8.3' if ansible_distribution == 'Ubuntu' else '8.4' }}"
zabbix_php_fpm_service: "php{{ zabbix_php_version }}-fpm"
zabbix_server_packages:
  - zabbix-server-pgsql
  - zabbix-frontend-php
  - zabbix-nginx-conf
  - zabbix-sql-scripts
  - zabbix-agent2
  - "postgresql-client-{{ postgresql_version | default(17) }}"
  - "php{{ zabbix_php_version }}-pgsql"
  - locales
zabbix_server_db_host: localhost
zabbix_server_db_port: 5432
zabbix_server_db_name: zabbix
zabbix_server_db_user: zabbix
zabbix_server_initialize_schema: true
zabbix_server_nginx_listen: 8080
zabbix_server_nginx_server_name: _
zabbix_server_service_name: zabbix-server
zabbix_server_agent_service_name: zabbix-agent2
